name: Commit
description: Commits the build
inputs:
  project:
    required: true
    description: The output of the check action

# TODO: make this a post action of restore
runs:
  using: composite
  steps:
    # Using a different version of tar from windows causes a cache miss with linux
    # https://github.com/actions/cache/issues/576#issuecomment-830796954
    - name: "Use GNU tar instead BSD tar"
      shell: cmd
      run: |
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      if: runner.os == 'Windows'

    # zstd 1.5.4 broke actions/toolkit https://github.com/actions/toolkit/issues/1341
    - if: runner.os == 'Windows'
      run: |
        if zstd --version | grep -q 'Zstandard CLI'; then
          choco install zstandard --version 1.5.0
          echo 'C:\ProgramData\chocolatey\bin'>>"$GITHUB_PATH"
        fi
      shell: bash
    - if: runner.os == 'Linux'
      run: |
        if zstd --version | grep -q 'Zstandard CLI'; then
          printf '#!/bin/sh\n'"$(which zstd)"' "$@" | sed "s/Zstandard CLI/zstd command line interface/g"' > "$RUNNER_TEMP/zstd"
          chmod +x "$RUNNER_TEMP/zstd"
          echo "$RUNNER_TEMP">>"$GITHUB_PATH"
        fi
      shell: bash

    # If zstd is missing a different compression method will be used
    # and cause a cache miss
    - run: which zstd
      shell: bash

    - name: Save cache
      uses: martijnhols/actions-cache/save@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{fromJson(inputs.project).path}}
        key: ${{fromJson(inputs.project).key}}
