name: Restore
description: Checks out, restores dependencies
inputs:
  path:
    required: false
    description: The paths to checkout
    default: ''
  dependencies:
    required: false
    description: The dependencies to restore (JSON list of JSON of the output of the check action)
    default: '[]'
  project:
    required: false
    description: The output of the check action (overrides path and dependencies)
    default: '{}'
  lfs:
    required: false
    description: Whether to download Git-LFS files
    default: 'false'

runs:
  using: composite
  steps:
    # Using a different version of tar from windows causes a cache miss with linux
    # https://github.com/actions/cache/issues/576#issuecomment-830796954
    - name: "Use GNU tar instead BSD tar"
      shell: cmd
      run: |
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      if: runner.os == 'Windows'

    # zstd 1.5.4 broke actions/toolkit https://github.com/actions/toolkit/issues/1341
    - if: runner.os == 'Windows'
      run: |
        if zstd --version | grep -q 'Zstandard CLI'; then
          choco install zstandard --version 1.5.0
          echo 'C:\ProgramData\chocolatey\bin'>>"$GITHUB_PATH"
        fi
      shell: bash
    - if: runner.os == 'Linux'
      run: |
        if zstd --version | grep -q 'Zstandard CLI'; then
          printf '#!/bin/sh\n'"$(which zstd)"' "$@" | sed "s/Zstandard CLI/zstd command line interface/g"' > "$RUNNER_TEMP/zstd"
          chmod +x "$RUNNER_TEMP/zstd"
          echo "$RUNNER_TEMP">>"$GITHUB_PATH"
        fi
      shell: bash

    # If zstd is missing a different compression method will be used
    # and cause a cache miss
    - run: which zstd
      shell: bash

    # TODO: make this sparse
    - uses: actions/checkout@v2
      with:
        lfs: ${{inputs.lfs}}
      if: (inputs.project == '{}' && inputs.path || fromJson(inputs.project).path) != ''

    # Dependencies
    - name: Restore dependency 0
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[0] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[0].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[0].key }}
        required: true
    - name: Restore dependency 1
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[1] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[1].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[1].key }}
        required: true
    - name: Restore dependency 2
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[2] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[2].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[2].key }}
        required: true
    - name: Restore dependency 3
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[3] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[3].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[3].key }}
        required: true
    - name: Restore dependency 4
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[4] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[4].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[4].key }}
        required: true
    - name: Restore dependency 5
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[5] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[5].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[5].key }}
        required: true
    - name: Restore dependency 6
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[6] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[6].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[6].key }}
        required: true
    - name: Restore dependency 7
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[7] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[7].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[7].key }}
        required: true
    - name: Restore dependency 8
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[8] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[8].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[8].key }}
        required: true
    - name: Restore dependency 9
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[9] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[9].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[9].key }}
        required: true
    - name: Restore dependency 10
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[10] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[10].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[10].key }}
        required: true
    - name: Restore dependency 11 
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[11] != null }}
      uses: martijnhols/actions-cache/restore@204c5fc6f17f75fc56021276acb5aa4b6a051d8e
      with:
        path: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[11].path }}
        key: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[11].key }}
        required: true

    - name: Check max dependencies
      if: ${{ fromJson(inputs.project == '{}' && inputs.dependencies || fromJson(inputs.project).dependencies)[12] != null }}
      run: |
        echo more than 12 dependencies not currently supported
        exit 1
      shell: bash
